# Generated by Django 5.2.11 on 2026-03-20 11:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_login', models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(message='This field can only contain alphanumeric characters (a-z, A-Z, 0-9). No spaces or special characters allowed.', regex='^[a-zA-Z0-9]+$')])),
                ('user_role', models.CharField(max_length=50)),
                ('user_firstname', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='This field can only contain alphanumeric characters (a-z, A-Z, 0-9) and spaces. No special characters allowed.', regex='^[a-zA-Z0-9 ]+$')])),
                ('user_lastname', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='This field can only contain alphanumeric characters (a-z, A-Z, 0-9) and spaces. No special characters allowed.', regex='^[a-zA-Z0-9 ]+$')])),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='userImages/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('no_of_points', models.IntegerField(default=0, null=True)),
                ('no_of_awards', models.IntegerField(default=0, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AwardsTable',
            fields=[
                ('award_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('award_name', models.CharField(max_length=200, unique=True)),
                ('award_description', models.TextField()),
                ('award_image', models.ImageField(blank=True, default=None, null=True, upload_to='awardImages/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ARTTable',
            fields=[
                ('art_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('art_name', models.CharField(max_length=200, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='art_manager_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SprintTable',
            fields=[
                ('sprint_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sprint_name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('quater', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(default='planned', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='elevate.arttable')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembersTable',
            fields=[
                ('employee_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NominationsTable',
            fields=[
                ('nomination_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comments', models.TextField()),
                ('nomination_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='elevate.awardstable')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='elevate.sprinttable')),
                ('nominator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='nominated_by', to='elevate.teammemberstable')),
                ('nominee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='elevate.teammemberstable')),
            ],
        ),
        migrations.CreateModel(
            name='TeamsTable',
            fields=[
                ('team_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=200)),
                ('team_description', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='elevate.arttable')),
            ],
        ),
        migrations.AddField(
            model_name='teammemberstable',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='elevate.teamstable'),
        ),
        migrations.CreateModel(
            name='JiraTasksTable',
            fields=[
                ('tasks_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tasks', models.JSONField(null=True)),
                ('no_of_points', models.IntegerField(default=0, null=True)),
                ('no_of_awards', models.IntegerField(default=0, null=True)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jira_tasks', to='elevate.sprinttable')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jira_tasks', to='elevate.teammemberstable')),
                ('team', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='jira_tasks', to='elevate.teamstable')),
            ],
        ),
    ]
